---
name: Check Cargo

on:
  pull_request:
    branches: [main]

env:
  # Extended support MSRV
  ROOT_PATH: bindings/rust/extended

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        id: toolchain
        run: |
          rustup toolchain install stable
          rustup override set stable

      # https://github.com/aws/aws-lc-rs/blob/main/aws-lc-fips-sys/README.md#build-prerequisites
      # go required for generate.sh to build aws-lc-rs in FIPS mode
      - name: Install go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.18'

      - uses: camshaft/rust-cache@v1

      - name: Generate
        run: ${{env.ROOT_PATH}}/generate.sh

      - name: Compare Cargo
        working-directory: ${{env.ROOT_PATH}}/s2n-tls-sys
        id: diff
        run: git diff --exit-code <(sort Cargo.toml) <(git show HEAD:${{env.ROOT_PATH}}/s2n-tls-sys/Cargo.toml | sort -)
        continue-on-error: true

      - name: Failure
        if: steps.diff.outcome != 'success'
        run: |
          echo "Please update the Cargo.toml in s2n-tls-sys"
          exit 1
